apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: final
  name: clo835
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: final
  name: clo835
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
  apiGroup: ""
roleRef:
  kind: Role
  name: clo835
  apiGroup: rbac.authorization.k8s.io
