apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: final
  labels:
    app: employee

spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee

  template:
    metadata:
      labels:
        app: employee

    spec:
      serviceAccountName: clo835
      containers:
        - name: application-container
          image: 
          imagePullPolicy: Always
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DBHOST
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DBUSER   
            - name: DBPORT
              value: "3306"
  
          envFrom:
            - configMapRef:
                name: clo835    
          ports:
            - containerPort: 81
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.5"
            
           
