apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql

spec:
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: database-container
          image: 061186295720.dkr.ecr.us-east-1.amazonaws.com/docker-prod-containers-database:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: my_database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DBUSER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DBPWD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DBHOST
            - name: MYSQL_PORT
              value: "3306"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: data-pvc
